version: "2"

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins-dind'
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - '8080:8080'
      - "50000:50000"
    volumes:
      - 'jenkins_data:/var/jenkins_home'
  nexus:
    image: sonatype/nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"

volumes:
  nexus-data: {}
  jenkins_data:
    driver: local