version: '2'
services:
  jenkins:
    build: .
    container_name: 'jenkins-dind'
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - '8080:8080'
      - "50000:50000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_data:/var/jenkins_home'
volumes:
  jenkins_data:
    driver: local